language: go
sudo: required
dist: trusty

go:
  - "1.10"

before_script:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
  - ip addr
  - sudo ping6 -c 1 ::1
  - sudo ping -c 1 127.0.0.1
  - sudo ping -c 1 127.0.0.2
  - sudo ping -c 1 127.0.0.3
  - sudo ping -c 1 127.0.0.4
  - sudo ping -c 1 127.0.0.5

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service="travis-ci" -race -flags="-exec=sudo" -flags="-timeout=5m"
