language: go
sudo: required
dist: trusty

go:
  - "1.10"

before_install:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -flags="-exec" -flags="sudo" -flags="-timeout" -flags="5m" -show -v
